project:
  type: website
  output-dir: docs

website:
  google-analytics:
    tracking-id: "G-W9VH0D4BP1"
  open-graph: true
  title: "Vector"
  favicon: favicon.ico
  navbar:
    background: dark
    left:
      - text: AM
        file: index.qmd
      - text: Статьи
        file: posts/index.html
  #    - text: Знания
  #      file: knowledge.html
      - text: Сервисы
        file: services.html
  #    - text: Сообщество
  #      file: social.html
      # - text: Доступ
      #  file: access.html
      
    #  - text: Услуги
     #   menu:
        
        #  text: Статьи
        #  file: posts/index.html
       # - text: Знания
      #    file: knowledge.html
      #  - text: Сервисы
      #    file: services.html
      #  - text: Сообщество
      #    file: social.html
      #  - text: Доступ
      #    file: access.html
          
    #  - text: Статьи
    #    file: posts/index.html

    # right:
  #    - text: Контакты
  #      menu:   
          
  #        - icon: envelope-fill
  #          text: Mail
  #          href: mailto:info@vector-am.ru
  #        - icon: github
  #          text: Github
  #          href: https://github.com/Ragve-hub
  #        - icon: substack 
  #          text: Substack
  #          href: https://qtreport.substack.com/
    
    
    
    
    # logo: black_final.png
    tools:
    - icon: envelope-fill
      href: mailto:info@vector-am.ru
    - icon: github
      href: https://github.com/Ragve-hub
    - icon: substack 
      href: https://qtreport.substack.com/
    #   - icon: plus-circle-fill
    #    href: https://forms.gle/2b8XDbXgsbq8uULp8
    
    
    
     

      
  page-footer: 
    left: "© 2003-2025, Qt" 
      - text: "О себе"
        href: about.html
      - text: "О сайте"
        href: about_site.html
      - text: "Дисклеймер"
        href: disclaimer.html
    
    right:
      - icon: envelope-fill
        href: mailto:info@vector-am.ru
      - icon: github
        href: https://github.com/Ragve-hub
      - icon: substack 
        href: https://qtreport.substack.com/ 
    #  - icon: plus-circle-fill
    #    href: https://forms.gle/2b8XDbXgsbq8uULp8

    
        
format:
  html:
    theme: seem.scss
    highlight-style: seem.theme
    # other-links:
    #  - href: posts/index.html
    #    icon: bookmark
    #    text: Статьи


    #  - href: knowledge.html
    #    icon: book
    #    text: Знания

     # - href: services.html
    #    icon: activity
    #    text: Сервисы
      
     # - href: social.html
    #    icon: flag
    #    text: Сообщество
        
     # - href: access.html
    #    icon: plus-circle
    #    text: Доступ


  # pdf:
  #  link-citations: true
  #  number-sections: false

#  docx:
#    reference-doc: custom-reference.docx
   
metadata:
   # pagetitle: "{{< meta title >}}"
   # freeze: true
   # title-block-banner: false
     # author: Vector
     # Can't yet enable this because it causes "On this page" to appear on index.html
     # even if I set its post-level `toc: false`
  toc: true
     # title-block-categories: false
     # toc-depth: 5

  



