---
title: "Сообщество"
toc: true
---

## Про сервер
Структура дискорд-сервера представляет собой структуру небольшого квант фонда/квант группы, с минимальной инфраструктурой и численностью персонала. Сервер создан для совместной работы по схеме win-win.

В процессе работы мы создаем торговые стратегии, которые сразу можно использовать в продакшн. Тем самым вы экономите не только свои деньги, но и примерно три/четыре года самообучения.


## Правила поведения на сервере

## Общие правила
1.1 Правила сервера имеют преимущество над другими правилами в случае каких-либо совпадений.

1.2 Администраторы могут дополнять/видоизменять их.

## Использование каналов
1.3 Текстовые и голосовые каналы должны использоваться только по их назначению.

1.4 Команды бота должны использоваться только в каналах для ботов.

1.5 Предложения напрямую влияющие на сервер можно обсуждать напрямую в личке с администраторами.

## Строго запрещено:
1.6 Спам, флуд (сообщения, смайлики, реакции, картинки, GIF). Если вы злоупотребляете, вы считаетесь спамером.

1.7 Использование ненужных тегов и тегов-призраков для пользователей и сотрудников,включая теги без сообщений.

1.8 Использовать теги @everyone и @here.

1.9 Аргументы, которые приводят к ссорам, и обсуждение политических вопросов.

2.0 Публикация информации, позволяющей установить личность пользователей или вас самих не допускается, независимо от обстоятельств.

2.1 Упрашивать других пользователей купить или подарить вам что-либо.

2.2 Реклама других серверов Discord, через коды приглашений, сокращённых URL-адресов или включая любые способы в любом медиа-контенте.

2.3 Реклама любых сервисов (бесплатных или платных), включая рекламу с использованием псевдонимов или медиа, загруженной в любом из каналов.

2.4 Отправка приглашений и/или рекламных объявлений другим лицам без предварительного уведомления посредством прямых сообщений.

## Реклама
2.5 Реклама не допускается, за исключением одобренной администраторами.

## Имена и никнеймы
2.6 Ваш ник должен содержать буквы алфавита, буквенно-цифровые символы, прописные или строчные. В нике допускается использование смайлов, если в вашем нике присутствует несколько буквенно-цифровых символов.

2.7 Ники не могут содержать ссылку на сайт

## Неприемлемый контент
2.8 Публикация любого неприемлемого контента, неподходящим или порнографическим содержанием, изображений, видео или звуков такого рода. Сюда также относятся смайлики,которые поощряют, стимулируют или предлагают любой половой акт, орган или что-либо связанное с этим.

2.9 Распространение вложений или ссылок, содержащих вирусы, вредоносные программы,и т.д., которые считаются незаконными в соответствии с международным правом.

3.0 Использование IP-трекеров или других вредоносных инструментов не допускается. Обсуждение или предложение использовать вышеуказанное не разрешается.

3.1 В любом канале / подканале запрещена публикация ссылок на донат-сайты, площадки приема платежей, спонсорской помощи, пожертвований и других сервисов.

3.2 Трансляция стримов не допускается.

## Система наказаний
3.3 Наказания действуют следующим образом: * устное предупреждение * постоянный бан.

3.4 Наказания сохраняются за вашим аккаунтом, и если вы переключаетесь на другой аккаунт Discord, ваши предыдущие наказания будут по-прежнему применяться.

3.5 Наказания не имеют срока давности. При необходимости могут быть сделаны исключения в стандартной процедуре наказаний.

## Роли на сервере

@everyone - Все кто зашел на сервер впервые.

@Разработчик - участники сервера имеющие доступ к research & develop

@Администратор - администраторы

## Доступ к серверу

Предоставление доступа после заполнения анкеты и оплаты

